name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: git fetch --all
      - run: git checkout main
      - run: git pull
      - run: git checkout release
      - run: git merge main
      - run: npm run build --if-present
      - run: git add dist -f
      - run: git commit --allow-empty -m "New Release"
      - run: git push release
